# Generated by Django 5.2.6 on 2025-10-28 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatmapdata',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_data', to='companies.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='companies.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='report',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='statisticssummary',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='companies.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trend_analyses', to='companies.company', verbose_name='Entreprise'),
        ),
    ]
