# Generated by Django 5.2.6 on 2025-11-03 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('monitoring', '0004_eventtype_companyeventtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], default='csv', max_length=10)),
                ('filter_data', models.JSONField(verbose_name='Critères de filtre appliqués')),
                ('date_from', models.DateTimeField(verbose_name='Date de début')),
                ('date_to', models.DateTimeField(verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin du fichier')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Taille du fichier')),
                ('record_count', models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'enregistrements")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_exports', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Export d'historique",
                'verbose_name_plural': "Exports d'historique",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.PositiveIntegerField(default=365, help_text='Nombre de jours avant archivage automatique', verbose_name='Durée de rétention (jours)')),
                ('auto_archive', models.BooleanField(default=True, verbose_name='Archivage automatique')),
                ('track_views', models.BooleanField(default=False, help_text='Enregistrer les actions de consultation/lecture', verbose_name='Traquer les consultations')),
                ('track_exports', models.BooleanField(default=True, verbose_name='Traquer les exports')),
                ('track_system_actions', models.BooleanField(default=False, verbose_name='Traquer les actions système')),
                ('enabled_categories', models.JSONField(default=list, help_text='Liste des catégories à historiser', verbose_name='Catégories activées')),
                ('notify_sensitive_actions', models.BooleanField(default=True, verbose_name='Notifier les actions sensibles')),
                ('notification_emails', models.JSONField(default=list, help_text='Liste des emails à notifier pour les actions sensibles', verbose_name='Emails de notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_settings', to='companies.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "Paramètres d'historique",
                'verbose_name_plural': "Paramètres d'historique",
            },
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('view', 'Consultation'), ('export', 'Exportation'), ('import', 'Importation'), ('activate', 'Activation'), ('deactivate', 'Désactivation'), ('assign', 'Attribution'), ('unassign', "Retrait d'attribution")], max_length=20, verbose_name='Action')),
                ('category', models.CharField(choices=[('user', 'Utilisateur'), ('company', 'Entreprise'), ('location', 'Localisation'), ('zone', 'Zone'), ('camera', 'Caméra'), ('alert', 'Alerte'), ('detection', 'Détection'), ('incident', 'Incident'), ('recording', 'Enregistrement'), ('settings', 'Paramètres'), ('system', 'Système'), ('auth', 'Authentification'), ('report', 'Rapport'), ('notification', 'Notification')], max_length=20, verbose_name='Catégorie')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_name', models.CharField(help_text="Nom/titre de l'objet modifié", max_length=255, verbose_name="Nom de l'objet")),
                ('description', models.TextField(help_text="Description détaillée de l'action", verbose_name='Description')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Anciennes valeurs')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Nouvelles valeurs')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='Champs modifiés')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clé de session')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='Données sensibles')),
                ('is_system_action', models.BooleanField(default=False, verbose_name='Action système')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='companies.company', verbose_name='Entreprise')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='monitoring.location', verbose_name='Localisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Entrée d'historique",
                'verbose_name_plural': "Entrées d'historique",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='history_his_timesta_7baf65_idx'), models.Index(fields=['user', 'timestamp'], name='history_his_user_id_84dd55_idx'), models.Index(fields=['company', 'timestamp'], name='history_his_company_fa541b_idx'), models.Index(fields=['category', 'timestamp'], name='history_his_categor_6d802c_idx'), models.Index(fields=['action', 'timestamp'], name='history_his_action_29c5d9_idx'), models.Index(fields=['content_type', 'object_id'], name='history_his_content_5a4045_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du filtre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('filter_data', models.JSONField(verbose_name='Données de filtre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False, verbose_name='Filtre par défaut')),
                ('is_shared', models.BooleanField(default=False, verbose_name="Partagé avec l'équipe")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Filtre d'historique",
                'verbose_name_plural': "Filtres d'historique",
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
