# Generated by Django 5.2.6 on 2025-11-03 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_subcompany_companyuser_current_subcompany_and_more'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyentry',
            name='subcompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='companies.subcompany', verbose_name='Sous-entreprise'),
        ),
    ]
