# Generated by Django 5.2.6 on 2025-10-22 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('template_type', models.CharField(choices=[('alert_created', 'Alerte créée'), ('alert_resolved', 'Alerte résolue'), ('system_status', 'Statut système'), ('maintenance', 'Maintenance'), ('security_breach', 'Violation de sécurité'), ('camera_offline', 'Caméra hors ligne'), ('daily_report', 'Rapport quotidien'), ('weekly_report', 'Rapport hebdomadaire')], max_length=30)),
                ('subject_template', models.CharField(max_length=200, verbose_name='Modèle de sujet')),
                ('body_template', models.TextField(verbose_name='Modèle de contenu')),
                ('variables', models.JSONField(default=dict, help_text='Variables disponibles')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template de notification',
                'verbose_name_plural': 'Templates de notification',
                'db_table': 'alerts_notification_template',
            },
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='notificationchannel',
            name='last_used',
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Notification Push'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('webhook', 'Webhook'), ('in_app', 'Notification In-App')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='configuration',
            field=models.JSONField(help_text='Configuration du canal (endpoints, tokens, etc.)'),
        ),
        migrations.AlterModelTable(
            name='notificationchannel',
            table='alerts_notification_channel',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('success', 'Succès'), ('alert', 'Alerte'), ('system', 'Système')], default='info', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Critique'), (2, 'Élevée'), (3, 'Normale'), (4, 'Faible')], default=3)),
                ('user_group', models.CharField(blank=True, help_text="Groupe d'utilisateurs", max_length=50)),
                ('metadata', models.JSONField(default=dict, help_text='Données supplémentaires')),
                ('channels_sent', models.JSONField(default=list, help_text="Canaux utilisés pour l'envoi")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('delivered', 'Délivrée'), ('read', 'Lue'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, help_text="URL d'action")),
                ('action_label', models.CharField(blank=True, help_text="Libellé du bouton d'action", max_length=50)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alerts.alert')),
                ('detection_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.detectionevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'alerts_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immédiat'), ('hourly', 'Toutes les heures'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('never', 'Jamais')], default='immediate', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Début des heures silencieuses', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Fin des heures silencieuses', null=True)),
                ('min_priority', models.IntegerField(choices=[(1, 'Critique'), (2, 'Élevée'), (3, 'Normale'), (4, 'Faible')], default=3, help_text='Priorité minimale pour recevoir des notifications')),
                ('enable_sound', models.BooleanField(default=True)),
                ('enable_vibration', models.BooleanField(default=True)),
                ('enable_email_digest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_channels', models.ManyToManyField(blank=True, related_name='alert_users', to='alerts.notificationchannel')),
                ('report_channels', models.ManyToManyField(blank=True, related_name='report_users', to='alerts.notificationchannel')),
                ('system_channels', models.ManyToManyField(blank=True, related_name='system_users', to='alerts.notificationchannel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
                'db_table': 'alerts_notification_preference',
            },
        ),
        migrations.DeleteModel(
            name='AlertRecipient',
        ),
        migrations.DeleteModel(
            name='NotificationLog',
        ),
    ]
