# Generated by Django 5.2.6 on 2025-10-28 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_notificationtemplate_remove_notificationlog_alert_and_more'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='companies.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='companies.company', verbose_name='Entreprise'),
        ),
    ]
