# Generated by Django 5.2.6 on 2025-10-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_company_alertrule_company'),
        ('monitoring', '0003_location_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertrule',
            name='location',
        ),
        migrations.AddField(
            model_name='alertrule',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='monitoring.zone', verbose_name='Zone'),
        ),
    ]
