# Generated by Django 5.2.6 on 2025-10-28 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_remove_alertrule_location_alertrule_zone'),
        ('monitoring', '0004_eventtype_companyeventtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('priority_override', models.IntegerField(blank=True, help_text='Laissez vide pour utiliser la priorité de la règle', null=True, verbose_name='Priorité personnalisée')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='alerts.alertrule', verbose_name="Règle d'alerte")),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='monitoring.camera', verbose_name='Caméra')),
            ],
            options={
                'verbose_name': "Règle d'alerte de caméra",
                'verbose_name_plural': "Règles d'alerte de caméras",
                'ordering': ['camera__name', 'alert_rule__name'],
                'unique_together': {('camera', 'alert_rule')},
            },
        ),
    ]
