# Generated by Django 5.2.6 on 2025-11-03 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_add_camera_alert_rule'),
        ('companies', '0002_subcompany_companyuser_current_subcompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='subcompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='companies.subcompany', verbose_name='Sous-entreprise'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='subcompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='companies.subcompany', verbose_name='Sous-entreprise'),
        ),
    ]
