# Generated by Django 5.2.6 on 2025-10-28 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('reference', models.CharField(help_text='Référence unique générée automatiquement', max_length=20, unique=True, verbose_name='Référence unique')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('is_active', models.BooleanField(default=True, verbose_name='Entreprise active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_users', models.PositiveIntegerField(default=50, verbose_name="Nombre maximum d'utilisateurs")),
                ('max_cameras', models.PositiveIntegerField(default=20, verbose_name='Nombre maximum de caméras')),
                ('max_locations', models.PositiveIntegerField(default=5, verbose_name='Nombre maximum de lieux')),
                ('settings', models.JSONField(default=dict, help_text="Configuration spécifique à l'entreprise", verbose_name='Paramètres personnalisés')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_policy', models.JSONField(default=dict, help_text='Politique de mots de passe (longueur min, complexité, etc.)')),
                ('session_timeout', models.PositiveIntegerField(default=7200, help_text='Timeout de session en secondes')),
                ('max_login_attempts', models.PositiveIntegerField(default=5, help_text='Nombre maximum de tentatives de connexion')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('ai_confidence_threshold', models.FloatField(default=0.75, help_text="Seuil de confiance pour l'IA")),
                ('auto_archive_days', models.PositiveIntegerField(default=90, help_text='Archivage automatique après X jours')),
                ('max_storage_gb', models.PositiveIntegerField(default=100, help_text='Stockage maximum en GB')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='light', max_length=20)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10)),
                ('timezone', models.CharField(default='Europe/Paris', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='companies.company')),
            ],
            options={
                'verbose_name': "Paramètres d'entreprise",
                'verbose_name_plural': "Paramètres d'entreprise",
            },
        ),
        migrations.CreateModel(
            name='CompanyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name="Email de l'invité")),
                ('role', models.CharField(choices=[('owner', "Propriétaire de l'application"), ('manager', "Manager d'entreprise"), ('employee', 'Employé'), ('viewer', 'Observateur')], default='employee', max_length=20)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée'), ('expired', 'Expirée')], default='pending', max_length=20)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_cameras', models.BooleanField(default=False)),
                ('can_manage_alerts', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='companies.company')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Invitation d'entreprise",
                'verbose_name_plural': "Invitations d'entreprise",
                'ordering': ['-created_at'],
                'unique_together': {('company', 'email', 'status')},
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', "Propriétaire de l'application"), ('manager', "Manager d'entreprise"), ('employee', 'Employé'), ('viewer', 'Observateur')], default='employee', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50, verbose_name='ID employé')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Utilisateur actif')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Peut gérer les utilisateurs')),
                ('can_manage_cameras', models.BooleanField(default=False, verbose_name='Peut gérer les caméras')),
                ('can_manage_alerts', models.BooleanField(default=False, verbose_name='Peut gérer les alertes')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='Peut voir les rapports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_company', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Utilisateur d'entreprise",
                'verbose_name_plural': "Utilisateurs d'entreprise",
                'ordering': ['company__name', 'user__last_name', 'user__first_name'],
                'unique_together': {('user', 'company')},
            },
        ),
    ]
