# Generated by Django 5.2.6 on 2025-11-03 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la sous-entreprise')),
                ('reference', models.CharField(help_text='Référence unique générée automatiquement', max_length=30, unique=True, verbose_name='Référence unique')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sous-entreprise active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Sous-entreprise par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_users', models.PositiveIntegerField(default=20, verbose_name="Nombre maximum d'utilisateurs")),
                ('max_cameras', models.PositiveIntegerField(default=10, verbose_name='Nombre maximum de caméras')),
                ('max_locations', models.PositiveIntegerField(default=3, verbose_name='Nombre maximum de lieux')),
                ('settings', models.JSONField(default=dict, help_text='Configuration spécifique à la sous-entreprise', verbose_name='Paramètres personnalisés')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcompanies', to='companies.company', verbose_name='Entreprise parente')),
            ],
            options={
                'verbose_name': 'Sous-entreprise',
                'verbose_name_plural': 'Sous-entreprises',
                'ordering': ['parent_company__name', 'name'],
                'unique_together': {('parent_company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='companyuser',
            name='current_subcompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='companies.subcompany', verbose_name='Sous-entreprise courante'),
        ),
        migrations.CreateModel(
            name='SubCompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Peut gérer les utilisateurs')),
                ('can_manage_cameras', models.BooleanField(default=False, verbose_name='Peut gérer les caméras')),
                ('can_manage_alerts', models.BooleanField(default=False, verbose_name='Peut gérer les alertes')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='Peut voir les rapports')),
                ('can_manage_locations', models.BooleanField(default=False, verbose_name='Peut gérer les localisations')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Assignation active')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcompany_assignments', to='companies.companyuser')),
                ('subcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcompany_users', to='companies.subcompany')),
            ],
            options={
                'verbose_name': 'Assignation sous-entreprise',
                'verbose_name_plural': 'Assignations sous-entreprises',
                'ordering': ['subcompany__name', 'company_user__user__username'],
                'unique_together': {('company_user', 'subcompany')},
            },
        ),
        migrations.AddField(
            model_name='companyuser',
            name='subcompanies',
            field=models.ManyToManyField(blank=True, related_name='users', through='companies.SubCompanyUser', to='companies.subcompany', verbose_name='Sous-entreprises'),
        ),
    ]
