# Generated by Django 5.2.6 on 2025-11-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_subcompany_companyuser_current_subcompany_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcompanyuser',
            name='can_manage_cameras',
        ),
        migrations.RemoveField(
            model_name='subcompanyuser',
            name='can_manage_locations',
        ),
        migrations.RemoveField(
            model_name='subcompanyuser',
            name='can_manage_users',
        ),
        migrations.AddField(
            model_name='subcompanyuser',
            name='can_manage_alert_rules',
            field=models.BooleanField(default=False, verbose_name="Règles d'alerte"),
        ),
        migrations.AddField(
            model_name='subcompanyuser',
            name='can_manage_monitoring',
            field=models.BooleanField(default=False, verbose_name='Surveillance (Caméras, Zones, Localisations)'),
        ),
        migrations.AlterField(
            model_name='subcompanyuser',
            name='can_manage_alerts',
            field=models.BooleanField(default=False, verbose_name='Gérer les alertes'),
        ),
        migrations.AlterField(
            model_name='subcompanyuser',
            name='can_view_reports',
            field=models.BooleanField(default=True, verbose_name='Voir les rapports'),
        ),
    ]
