# Generated by Django 5.2.6 on 2025-11-04 09:35

import companies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_simplify_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeCibleImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lot', models.CharField(help_text="Nom descriptif pour ce lot d'import", max_length=200, verbose_name='Nom du lot')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('total_images', models.PositiveIntegerField(default=0, verbose_name="Total d'images")),
                ('images_traitees', models.PositiveIntegerField(default=0, verbose_name='Images traitées')),
                ('images_reussies', models.PositiveIntegerField(default=0, verbose_name='Images réussies')),
                ('images_echouees', models.PositiveIntegerField(default=0, verbose_name='Images échouées')),
                ('status', models.CharField(choices=[('uploading', 'Upload en cours'), ('processing', 'Traitement en cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='uploading', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('logs', models.JSONField(default=list, help_text='Historique des opérations', verbose_name='Logs de traitement')),
                ('erreurs', models.JSONField(default=list, help_text='Liste des erreurs durant le traitement', verbose_name='Erreurs rencontrées')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='companies.company', verbose_name='Entreprise')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('subcompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='companies.subcompany', verbose_name='Sous-entreprise')),
            ],
            options={
                'verbose_name': "Lot d'import d'employés",
                'verbose_name_plural': "Lots d'import d'employés",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeCible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_originale', models.ImageField(help_text='Image importée par le système', upload_to=companies.models.upload_employee_image, verbose_name='Image originale')),
                ('image_miniature', models.ImageField(blank=True, help_text='Miniature générée automatiquement', null=True, upload_to=companies.models.upload_employee_image, verbose_name='Miniature')),
                ('image_visage', models.ImageField(blank=True, help_text="Visage extrait par l'IA", null=True, upload_to=companies.models.upload_employee_image, verbose_name='Visage extrait')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('employee_id', models.CharField(blank=True, help_text="Identifiant unique de l'employé", max_length=50, verbose_name='ID Employé')),
                ('poste', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('departement', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('validated', 'Validé'), ('rejected', 'Rejeté'), ('archived', 'Archivé')], default='pending', max_length=20, verbose_name='Statut')),
                ('detection_status', models.CharField(choices=[('not_processed', 'Non traité'), ('processing', 'En cours de traitement'), ('face_detected', 'Visage détecté'), ('no_face_detected', 'Aucun visage détecté'), ('multiple_faces', 'Plusieurs visages détectés'), ('low_quality', 'Qualité insuffisante')], default='not_processed', max_length=20, verbose_name='Statut de détection')),
                ('image_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Largeur image')),
                ('image_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hauteur image')),
                ('image_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille fichier (bytes)')),
                ('image_format', models.CharField(blank=True, max_length=10, verbose_name='Format image')),
                ('face_encoding', models.JSONField(blank=True, help_text="Données d'encodage facial pour la reconnaissance", null=True, verbose_name='Encodage facial')),
                ('face_landmarks', models.JSONField(blank=True, help_text='Points de repère du visage détectés', null=True, verbose_name='Points faciaux')),
                ('detection_confidence', models.FloatField(blank=True, help_text='Score de confiance de la détection faciale (0-1)', null=True, verbose_name='Confiance de détection')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_priority', models.BooleanField(default=False, verbose_name='Prioritaire')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes_cibles', to='companies.company', verbose_name='Entreprise')),
                ('importe_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes_cibles_importes', to=settings.AUTH_USER_MODEL, verbose_name='Importé par')),
                ('subcompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employes_cibles', to='companies.subcompany', verbose_name='Sous-entreprise')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes_cibles_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Employé ciblé',
                'verbose_name_plural': 'Employés ciblés',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='companies_e_company_9a879f_idx'), models.Index(fields=['subcompany', 'status'], name='companies_e_subcomp_8f098c_idx'), models.Index(fields=['detection_status'], name='companies_e_detecti_bcdc92_idx'), models.Index(fields=['created_at'], name='companies_e_created_cd944f_idx')],
            },
        ),
    ]
