# Generated by Django 5.2.6 on 2025-12-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_employecibleimportbatch_employecible'),
    ]

    operations = [
        migrations.AddField(
            model_name='employecible',
            name='employee_group',
            field=models.ForeignKey(blank=True, help_text='Premier enregistrement du groupe pour regrouper les images du même employé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_images', to='companies.employecible', verbose_name="Groupe d'employé"),
        ),
    ]
