# Generated by Django 5.2.6 on 2025-09-24 09:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la caméra')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('port', models.PositiveIntegerField(default=554)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('stream_url', models.URLField(help_text='URL de streaming RTSP/HTTP')),
                ('status', models.CharField(choices=[('online', 'En ligne'), ('offline', 'Hors ligne'), ('maintenance', 'Maintenance'), ('error', 'Erreur')], default='offline', max_length=20)),
                ('resolution', models.CharField(default='1920x1080', max_length=20)),
                ('fps', models.PositiveIntegerField(default=30)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_ai_enabled', models.BooleanField(default=True, verbose_name='IA activée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caméra',
                'verbose_name_plural': 'Caméras',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du lieu')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('intrusion', 'Intrusion'), ('theft', 'Vol'), ('suspicious', 'Comportement suspect'), ('abandoned_object', 'Objet abandonné'), ('accident', 'Accident'), ('fire', 'Incendie'), ('crowd', 'Attroupement'), ('violence', 'Violence'), ('vandalism', 'Vandalisme'), ('weapon', 'Arme détectée')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=10)),
                ('confidence', models.FloatField(help_text="Niveau de confiance de l'IA (0.0-1.0)")),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bounding_boxes', models.JSONField(help_text='Coordonnées des objets détectés')),
                ('description', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('video_clip_path', models.CharField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('false_positive', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='monitoring.camera')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Détection',
                'verbose_name_plural': 'Détections',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'incident")),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('investigating', "En cours d'investigation"), ('resolved', 'Résolu'), ('closed', 'Fermé'), ('false_alarm', 'Fausse alarme')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('detections', models.ManyToManyField(related_name='incidents', to='monitoring.detectionevent')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitoring.location')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='monitoring.location'),
        ),
        migrations.CreateModel(
            name='VideoRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(help_text='Taille en bytes')),
                ('duration_seconds', models.PositiveIntegerField()),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='monitoring.camera')),
                ('detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.detectionevent')),
            ],
            options={
                'verbose_name': 'Enregistrement',
                'verbose_name_plural': 'Enregistrements',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('risk_level', models.CharField(choices=[('high', 'Risque élevé'), ('medium', 'Risque moyen'), ('low', 'Risque faible')], default='medium', max_length=10)),
                ('coordinates', models.JSONField(help_text='Coordonnées de la zone [x1,y1,x2,y2]')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='monitoring.location')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='monitoring.zone'),
        ),
        migrations.AddField(
            model_name='camera',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='monitoring.zone'),
        ),
    ]
