# Generated by Django 5.2.6 on 2025-10-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='ip_address',
            field=models.CharField(help_text='Adresse IP (ex: 192.168.1.100) ou URL complète', max_length=255, verbose_name='Adresse IP ou URL'),
        ),
    ]
