# Generated by Django 5.2.6 on 2025-10-28 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('monitoring', '0002_alter_camera_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companies.company', verbose_name='Entreprise'),
        ),
    ]
