# Generated by Django 5.2.6 on 2025-10-28 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('monitoring', '0003_location_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du type')),
                ('code', models.CharField(help_text="Code technique utilisé par l'IA (ex: intrusion, theft)", max_length=50, unique=True, verbose_name='Code unique')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='medium', max_length=20, verbose_name='Gravité par défaut')),
                ('color', models.CharField(default='#007bff', help_text="Couleur d'affichage (format hex: #RRGGBB)", max_length=7, verbose_name='Couleur')),
                ('icon', models.CharField(default='fas fa-exclamation-triangle', help_text="Classe CSS de l'icône FontAwesome", max_length=50, verbose_name='Icône')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_alert', models.BooleanField(default=True, help_text='Créer automatiquement une alerte lors de la détection', verbose_name='Alerte automatique')),
                ('requires_verification', models.BooleanField(default=False, help_text="L'événement doit être vérifié manuellement", verbose_name='Nécessite vérification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': "Type d'événement",
                'verbose_name_plural': "Types d'événements",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Activé')),
                ('custom_severity', models.CharField(blank=True, choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], help_text='Laissez vide pour utiliser la gravité par défaut', max_length=20, verbose_name='Gravité personnalisée')),
                ('custom_name', models.CharField(blank=True, help_text='Nom affiché pour cette entreprise', max_length=100, verbose_name='Nom personnalisé')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to='companies.company', verbose_name='Entreprise')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='monitoring.eventtype', verbose_name="Type d'événement")),
            ],
            options={
                'verbose_name': "Type d'événement d'entreprise",
                'verbose_name_plural': "Types d'événements d'entreprises",
                'ordering': ['company__name', 'event_type__name'],
                'unique_together': {('company', 'event_type')},
            },
        ),
    ]
